package system.ListMenuPackage;

/**
* system/ListMenuPackage/MenuNotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

public final class MenuNotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public system.ListMenuPackage.MenuNotFound value = null;

  public MenuNotFoundHolder ()
  {
  }

  public MenuNotFoundHolder (system.ListMenuPackage.MenuNotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = system.ListMenuPackage.MenuNotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    system.ListMenuPackage.MenuNotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return system.ListMenuPackage.MenuNotFoundHelper.type ();
  }

}
