package system.ListMenuPackage;


/**
* system/ListMenuPackage/MenuNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

public final class MenuNotFound extends org.omg.CORBA.UserException
{

  public MenuNotFound ()
  {
    super(MenuNotFoundHelper.id());
  } // ctor


  public MenuNotFound (String $reason)
  {
    super(MenuNotFoundHelper.id() + "  " + $reason);
  } // ctor

} // class MenuNotFound
