package system;


/**
* system/_ListMenuStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

public class _ListMenuStub extends org.omg.CORBA.portable.ObjectImpl implements system.ListMenu
{

  public void ajouterMenu (system.ListMenuLevel1Package.MenuP command)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ajouterMenu", false);
                system.ListMenuLevel1Package.MenuPHelper.write ($out, command);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                ajouterMenu (command        );
            } finally {
                _releaseReply ($in);
            }
  } // ajouterMenu

  public system.ListMenuLevel1Package.MenuP[] modifieMenu (system.ListMenuLevel1Package.MenuP menu, int id) throws system.ListMenuPackage.MenuNotFound
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("modifieMenu", true);
                system.ListMenuLevel1Package.MenuPHelper.write ($out, menu);
                $out.write_long (id);
                $in = _invoke ($out);
                system.ListMenuLevel1Package.MenuP $result[] = system.ListMenuLevel1Package.MenusHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:system/ListMenu/MenuNotFound:1.0"))
                    throw system.ListMenuPackage.MenuNotFoundHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return modifieMenu (menu, id        );
            } finally {
                _releaseReply ($in);
            }
  } // modifieMenu

  public void supprimeMenu (int menuid) throws system.ListMenuPackage.MenuNotFound
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("supprimeMenu", true);
                $out.write_long (menuid);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:system/ListMenu/MenuNotFound:1.0"))
                    throw system.ListMenuPackage.MenuNotFoundHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                supprimeMenu (menuid        );
            } finally {
                _releaseReply ($in);
            }
  } // supprimeMenu

  public system.ListMenuLevel1Package.MenuP[] getMenu ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMenu", true);
                $in = _invoke ($out);
                system.ListMenuLevel1Package.MenuP $result[] = system.ListMenuLevel1Package.MenusHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getMenu (        );
            } finally {
                _releaseReply ($in);
            }
  } // getMenu

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:system/ListMenu:1.0", 
    "IDL:system/ListMenuLevel1:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ListMenuStub
