package system;

/**
* system/emplyerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

public final class emplyerHolder implements org.omg.CORBA.portable.Streamable
{
  public system.emplyer value = null;

  public emplyerHolder ()
  {
  }

  public emplyerHolder (system.emplyer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = system.emplyerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    system.emplyerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return system.emplyerHelper.type ();
  }

}
