package system;


/**
* system/emplyer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

public final class emplyer implements org.omg.CORBA.portable.IDLEntity
{
  public String nom = null;
  public String motDepass = null;

  public emplyer ()
  {
  } // ctor

  public emplyer (String _nom, String _motDepass)
  {
    nom = _nom;
    motDepass = _motDepass;
  } // ctor

} // class emplyer
