package system;

/**
* system/ListCommandLivreurHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/


//****************************
public final class ListCommandLivreurHolder implements org.omg.CORBA.portable.Streamable
{
  public system.ListCommandLivreur value = null;

  public ListCommandLivreurHolder ()
  {
  }

  public ListCommandLivreurHolder (system.ListCommandLivreur initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = system.ListCommandLivreurHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    system.ListCommandLivreurHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return system.ListCommandLivreurHelper.type ();
  }

}
