package system;


/**
* system/ListCommandCuisinierHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/


//*********************
abstract public class ListCommandCuisinierHelper
{
  private static String  _id = "IDL:system/ListCommandCuisinier:1.0";

  public static void insert (org.omg.CORBA.Any a, system.ListCommandCuisinier that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static system.ListCommandCuisinier extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (system.ListCommandCuisinierHelper.id (), "ListCommandCuisinier");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static system.ListCommandCuisinier read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ListCommandCuisinierStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, system.ListCommandCuisinier value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static system.ListCommandCuisinier narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof system.ListCommandCuisinier)
      return (system.ListCommandCuisinier)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      system._ListCommandCuisinierStub stub = new system._ListCommandCuisinierStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static system.ListCommandCuisinier unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof system.ListCommandCuisinier)
      return (system.ListCommandCuisinier)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      system._ListCommandCuisinierStub stub = new system._ListCommandCuisinierStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
