package system;

/**
* system/ListCommandCuisinierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/


//*********************
public final class ListCommandCuisinierHolder implements org.omg.CORBA.portable.Streamable
{
  public system.ListCommandCuisinier value = null;

  public ListCommandCuisinierHolder ()
  {
  }

  public ListCommandCuisinierHolder (system.ListCommandCuisinier initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = system.ListCommandCuisinierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    system.ListCommandCuisinierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return system.ListCommandCuisinierHelper.type ();
  }

}
