package system;


/**
* system/ListCommandLevel1.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/


//*****************
public interface ListCommandLevel1 extends ListCommandLevel1Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ListCommandLevel1
