package system;

/**
* system/ListMenuLevel1Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/


//**********************
public final class ListMenuLevel1Holder implements org.omg.CORBA.portable.Streamable
{
  public system.ListMenuLevel1 value = null;

  public ListMenuLevel1Holder ()
  {
  }

  public ListMenuLevel1Holder (system.ListMenuLevel1 initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = system.ListMenuLevel1Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    system.ListMenuLevel1Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return system.ListMenuLevel1Helper.type ();
  }

}
