package system;


/**
* system/ListCommandLivreurPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/


//****************************
public abstract class ListCommandLivreurPOA extends org.omg.PortableServer.Servant
 implements system.ListCommandLivreurOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("livrer", new java.lang.Integer (0));
    _methods.put ("consulterAdress", new java.lang.Integer (1));
    _methods.put ("ajouterCommand", new java.lang.Integer (2));
    _methods.put ("supprimeCommand", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // system/ListCommandLivreur/livrer
       {
         try {
           int num = in.read_long ();
           this.livrer (num);
           out = $rh.createReply();
         } catch (system.ListCommandLevel1Package.CommandNotFound $ex) {
           out = $rh.createExceptionReply ();
           system.ListCommandLevel1Package.CommandNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // system/ListCommandLivreur/consulterAdress
       {
         try {
           int numdecommand = in.read_long ();
           String $result = null;
           $result = this.consulterAdress (numdecommand);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (system.ListCommandLevel1Package.CommandNotFound $ex) {
           out = $rh.createExceptionReply ();
           system.ListCommandLevel1Package.CommandNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // system/ListCommandLevel1/ajouterCommand
       {
         system.ListCommandLevel1Package.Command command = system.ListCommandLevel1Package.CommandHelper.read (in);
         int $result = (int)0;
         $result = this.ajouterCommand (command);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // system/ListCommandLevel1/supprimeCommand
       {
         try {
           int commandID = in.read_long ();
           this.supprimeCommand (commandID);
           out = $rh.createReply();
         } catch (system.ListCommandLevel1Package.CommandNotFound $ex) {
           out = $rh.createExceptionReply ();
           system.ListCommandLevel1Package.CommandNotFoundHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:system/ListCommandLivreur:1.0", 
    "IDL:system/ListCommandLevel1:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ListCommandLivreur _this() 
  {
    return ListCommandLivreurHelper.narrow(
    super._this_object());
  }

  public ListCommandLivreur _this(org.omg.CORBA.ORB orb) 
  {
    return ListCommandLivreurHelper.narrow(
    super._this_object(orb));
  }


} // class ListCommandLivreurPOA
