package system;


/**
* system/ListMenuLevel1Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/


//**********************
public interface ListMenuLevel1Operations 
{
  system.ListMenuLevel1Package.MenuP[] getMenu ();
} // interface ListMenuLevel1Operations
