package system;


/**
* system/ListCommandLivreurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/


//****************************
public interface ListCommandLivreurOperations  extends system.ListCommandLevel1Operations
{
  void livrer (int num) throws system.ListCommandLevel1Package.CommandNotFound;
  String consulterAdress (int numdecommand) throws system.ListCommandLevel1Package.CommandNotFound;
} // interface ListCommandLivreurOperations
