package system;


/**
* system/ListMenuOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

public interface ListMenuOperations  extends system.ListMenuLevel1Operations
{
  void ajouterMenu (system.ListMenuLevel1Package.MenuP command);
  system.ListMenuLevel1Package.MenuP[] modifieMenu (system.ListMenuLevel1Package.MenuP menu, int id) throws system.ListMenuPackage.MenuNotFound;
  void supprimeMenu (int menuid) throws system.ListMenuPackage.MenuNotFound;
} // interface ListMenuOperations
