package system;


/**
* system/ListMenuPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

public abstract class ListMenuPOA extends org.omg.PortableServer.Servant
 implements system.ListMenuOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ajouterMenu", new java.lang.Integer (0));
    _methods.put ("modifieMenu", new java.lang.Integer (1));
    _methods.put ("supprimeMenu", new java.lang.Integer (2));
    _methods.put ("getMenu", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // system/ListMenu/ajouterMenu
       {
         system.ListMenuLevel1Package.MenuP command = system.ListMenuLevel1Package.MenuPHelper.read (in);
         this.ajouterMenu (command);
         out = $rh.createReply();
         break;
       }

       case 1:  // system/ListMenu/modifieMenu
       {
         try {
           system.ListMenuLevel1Package.MenuP menu = system.ListMenuLevel1Package.MenuPHelper.read (in);
           int id = in.read_long ();
           system.ListMenuLevel1Package.MenuP $result[] = null;
           $result = this.modifieMenu (menu, id);
           out = $rh.createReply();
           system.ListMenuLevel1Package.MenusHelper.write (out, $result);
         } catch (system.ListMenuPackage.MenuNotFound $ex) {
           out = $rh.createExceptionReply ();
           system.ListMenuPackage.MenuNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // system/ListMenu/supprimeMenu
       {
         try {
           int menuid = in.read_long ();
           this.supprimeMenu (menuid);
           out = $rh.createReply();
         } catch (system.ListMenuPackage.MenuNotFound $ex) {
           out = $rh.createExceptionReply ();
           system.ListMenuPackage.MenuNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // system/ListMenuLevel1/getMenu
       {
         system.ListMenuLevel1Package.MenuP $result[] = null;
         $result = this.getMenu ();
         out = $rh.createReply();
         system.ListMenuLevel1Package.MenusHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:system/ListMenu:1.0", 
    "IDL:system/ListMenuLevel1:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ListMenu _this() 
  {
    return ListMenuHelper.narrow(
    super._this_object());
  }

  public ListMenu _this(org.omg.CORBA.ORB orb) 
  {
    return ListMenuHelper.narrow(
    super._this_object(orb));
  }


} // class ListMenuPOA
