package system;


/**
* system/ListCommandLivreur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/


//****************************
public interface ListCommandLivreur extends ListCommandLivreurOperations, system.ListCommandLevel1, org.omg.CORBA.portable.IDLEntity 
{
} // interface ListCommandLivreur
