package system;


/**
* system/ListCommandCuisinierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/


//*********************
public interface ListCommandCuisinierOperations  extends system.ListCommandLevel1Operations
{
  void Valide (int numerodeCommand) throws system.ListCommandLevel1Package.CommandNotFound;
  system.ListCommandLevel1Package.Command[] getCommands (String type);
  system.ListCommandLevel1Package.Command consulter (int numrodeCommand) throws system.ListCommandLevel1Package.CommandNotFound;
} // interface ListCommandCuisinierOperations
