package system;


/**
* system/ListMenu.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

public interface ListMenu extends ListMenuOperations, system.ListMenuLevel1, org.omg.CORBA.portable.IDLEntity 
{
} // interface ListMenu
