package system;

/**
* system/ListCommandLevel1Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/


//*****************
public final class ListCommandLevel1Holder implements org.omg.CORBA.portable.Streamable
{
  public system.ListCommandLevel1 value = null;

  public ListCommandLevel1Holder ()
  {
  }

  public ListCommandLevel1Holder (system.ListCommandLevel1 initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = system.ListCommandLevel1Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    system.ListCommandLevel1Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return system.ListCommandLevel1Helper.type ();
  }

}
