package system;

/**
* system/ListMenuHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

public final class ListMenuHolder implements org.omg.CORBA.portable.Streamable
{
  public system.ListMenu value = null;

  public ListMenuHolder ()
  {
  }

  public ListMenuHolder (system.ListMenu initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = system.ListMenuHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    system.ListMenuHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return system.ListMenuHelper.type ();
  }

}
