package system.ListMenuLevel1Package;


/**
* system/ListMenuLevel1Package/MenuP.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

public final class MenuP implements org.omg.CORBA.portable.IDLEntity
{
  public String entrée = null;
  public String plat = null;
  public String boisson = null;
  public String prix = null;
  public String id = null;

  public MenuP ()
  {
  } // ctor

  public MenuP (String _entrée, String _plat, String _boisson, String _prix, String _id)
  {
    entrée = _entrée;
    plat = _plat;
    boisson = _boisson;
    prix = _prix;
    id = _id;
  } // ctor

} // class MenuP
