package system.ListMenuLevel1Package;


/**
* system/ListMenuLevel1Package/MenuPHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

abstract public class MenuPHelper
{
  private static String  _id = "IDL:system/ListMenuLevel1/MenuP:1.0";

  public static void insert (org.omg.CORBA.Any a, system.ListMenuLevel1Package.MenuP that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static system.ListMenuLevel1Package.MenuP extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "entrée",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "plat",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "boisson",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "prix",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (system.ListMenuLevel1Package.MenuPHelper.id (), "MenuP", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static system.ListMenuLevel1Package.MenuP read (org.omg.CORBA.portable.InputStream istream)
  {
    system.ListMenuLevel1Package.MenuP value = new system.ListMenuLevel1Package.MenuP ();
    value.entrée = istream.read_string ();
    value.plat = istream.read_string ();
    value.boisson = istream.read_string ();
    value.prix = istream.read_string ();
    value.id = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, system.ListMenuLevel1Package.MenuP value)
  {
    ostream.write_string (value.entrée);
    ostream.write_string (value.plat);
    ostream.write_string (value.boisson);
    ostream.write_string (value.prix);
    ostream.write_string (value.id);
  }

}
