package system.ListCommandLevel1Package;

/**
* system/ListCommandLevel1Package/CommandNotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

public final class CommandNotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public system.ListCommandLevel1Package.CommandNotFound value = null;

  public CommandNotFoundHolder ()
  {
  }

  public CommandNotFoundHolder (system.ListCommandLevel1Package.CommandNotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = system.ListCommandLevel1Package.CommandNotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    system.ListCommandLevel1Package.CommandNotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return system.ListCommandLevel1Package.CommandNotFoundHelper.type ();
  }

}
