package system.ListCommandLevel1Package;


/**
* system/ListCommandLevel1Package/Command.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

public final class Command implements org.omg.CORBA.portable.IDLEntity
{
  public String etat = null;
  public String adressDeCommand = null;
  public String codeMenu = null;
  public String numeroDeCommand = null;

  public Command ()
  {
  } // ctor

  public Command (String _etat, String _adressDeCommand, String _codeMenu, String _numeroDeCommand)
  {
    etat = _etat;
    adressDeCommand = _adressDeCommand;
    codeMenu = _codeMenu;
    numeroDeCommand = _numeroDeCommand;
  } // ctor

} // class Command
