package system.ListCommandLevel1Package;


/**
* system/ListCommandLevel1Package/CommandNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

public final class CommandNotFound extends org.omg.CORBA.UserException
{

  public CommandNotFound ()
  {
    super(CommandNotFoundHelper.id());
  } // ctor


  public CommandNotFound (String $reason)
  {
    super(CommandNotFoundHelper.id() + "  " + $reason);
  } // ctor

} // class CommandNotFound
