package system.ListCommandLevel1Package;


/**
* system/ListCommandLevel1Package/CommandHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

abstract public class CommandHelper
{
  private static String  _id = "IDL:system/ListCommandLevel1/Command:1.0";

  public static void insert (org.omg.CORBA.Any a, system.ListCommandLevel1Package.Command that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static system.ListCommandLevel1Package.Command extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "etat",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "adressDeCommand",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "codeMenu",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "numeroDeCommand",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (system.ListCommandLevel1Package.CommandHelper.id (), "Command", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static system.ListCommandLevel1Package.Command read (org.omg.CORBA.portable.InputStream istream)
  {
    system.ListCommandLevel1Package.Command value = new system.ListCommandLevel1Package.Command ();
    value.etat = istream.read_string ();
    value.adressDeCommand = istream.read_string ();
    value.codeMenu = istream.read_string ();
    value.numeroDeCommand = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, system.ListCommandLevel1Package.Command value)
  {
    ostream.write_string (value.etat);
    ostream.write_string (value.adressDeCommand);
    ostream.write_string (value.codeMenu);
    ostream.write_string (value.numeroDeCommand);
  }

}
