package system.ListCommandCuisinierPackage;


/**
* system/ListCommandCuisinierPackage/CommandDidnotadded.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

public final class CommandDidnotadded extends org.omg.CORBA.UserException
{

  public CommandDidnotadded ()
  {
    super(CommandDidnotaddedHelper.id());
  } // ctor


  public CommandDidnotadded (String $reason)
  {
    super(CommandDidnotaddedHelper.id() + "  " + $reason);
  } // ctor

} // class CommandDidnotadded
