package system.ListCommandCuisinierPackage;

/**
* system/ListCommandCuisinierPackage/CommandDidnotaddedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from system.idl
* jeudi 8 janvier 2015 19 h 17 CET
*/

public final class CommandDidnotaddedHolder implements org.omg.CORBA.portable.Streamable
{
  public system.ListCommandCuisinierPackage.CommandDidnotadded value = null;

  public CommandDidnotaddedHolder ()
  {
  }

  public CommandDidnotaddedHolder (system.ListCommandCuisinierPackage.CommandDidnotadded initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = system.ListCommandCuisinierPackage.CommandDidnotaddedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    system.ListCommandCuisinierPackage.CommandDidnotaddedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return system.ListCommandCuisinierPackage.CommandDidnotaddedHelper.type ();
  }

}
